### ISSUE TITLE
Terraform plan is failing intermittently

### ISSUE THREAD

**Issue by seansund** [ibm-garage-cloud/terraform-tools-tekton-resources#44]
2021/04/20 09:18:31 Terraform plan | Warning: Interpolation-only expressions are deprecated
2021/04/20 09:18:31 Terraform plan |
2021/04/20 09:18:31 Terraform plan | on .terraform/modules/tekton-resources/main.tf line 32, in resource "null_resource" "tekton_resources":
2021/04/20 09:18:31 Terraform plan |
2021/04/20 09:18:31 Terraform plan | Error: open /tmp/tfws-728376125/.tmp/tekton-resources-version.val: no such file or directory
2021/04/20 09:18:31 Terraform plan |
2021/04/20 09:18:31 Terraform plan |
2021/04/20 09:18:31 Terraform plan | 32: TMP_DIR = "${local.tmp_dir}"

**Comment by seansund** [comment]
Should be fixed in [v2.2.14](https://github.com/cloud-native-toolkit/terraform-tools-tekton-resources/releases/tag/v2.2.14)

**Comment by csantanapr** [comment]
This is fix now
